### ISSUE TITLE
Questions about implementation of LOF

### ISSUE THREAD

**Issue by schonhose** [privefl/bigutilsr#7]
While searching for a function to determine outliers based on PCA scores I came across your implementation for LOF in the package `bigutilsr`. I have a couple of questions I hope you can help me with.

Your package uses multiple `k`-values and retains the maximum LOF value found for value of `k`. What I am wondering is what would be the best range of `k`? Especially in the interpretation of the LOF value itself.

I also looked at the function `lofactor()` in the `DMwR` package and while the outcome is very similar in terms of flagging outliers, there are numerical differences that I cannot seem to explain. As far as I know I have used the same parameters for both functions. I feel the drawback for this function is that only one `k`-value can be provided (hence, I did compare both outcomes with one singular `k`-value). One solution might be to use `NbClust` and use the outcome of that as the number of `k`.

Can you provide some information about the idea to combine the LOF results using the max and for suitable sequence of `k`-values?

**Comment by privefl** [comment]
Have you looked at my blog post on this? https://privefl.github.io/blog/detecting-outlier-samples-in-pca/
Actually, I'm using something slightly different in https://doi.org/10.1093/bioinformatics/btaa520 (see section 3.4).

The use of multiple values in `LOF()` is to make it robust to the choice of k. The right values depend a lot on the number of observations you have in your data and the sizes of the clusters I guess.

For the difference with package {DMwR}, I guess due to the sum of many small values, there can be imprecisions. I would say that my function should be more precise because I'm using `mean()` which should be more precise than `sum()`.
